export const ACTIONS = {
  JOIN: "join",
  JOINED: "joined",
  DISCONNECTED: "disconnected",
  BODY_CHANGE: "body-change",
  INPUT_CHANGE: "input-change",
  OUTPUT_CHANGE: "output-change",
  LANGUAGE_CHANGE: "langauge-change",
  SYNC_CODE: "sync-code",
  SAVE: "save",
  SAVED: "saved",
  RUN: "run",
  RUNNED: "runned",
  LEAVE: "leave",
};
